### PR TITLE
Added tox configuration

### PR DESCRIPTION
**Pull request by ZuluPro**
Useful for tests again Python 2.7-3.5, Django 1.6-1.9, PyPy and PyPy3.

### CODE REVIEW

**Comment by kylef** [comment]
This looks interesting, being able to test against multiple versions of Django.

I haven't played with tox much myself, is it possible to run tox in travis so that these versions are tested on CI? https://github.com/getpelican/pelican/blob/master/.travis.yml

**Comment by ZuluPro** [comment]
That is exactly what I plan.
I've made that in Django-dbbackup. ;)

Anthony Monthe - Open source enthousiaste
anthony-monthe.me

**Comment by ZuluPro** [comment]
@kylef @felixxm Rebased from master !
Do you want me to update Travis configuration ?

**Comment by ZuluPro** [comment]
@kylef @felixxm : I just rebased from master.

**Comment by ZuluPro** [comment]
@kylef @felixxm Any news ?

**Comment by ZuluPro** [comment]
@kylef @felixxm Any news ?

**Pull request closed without merging**
