### PR TITLE
Remove prefix REQUEST_ in settings.py for simply all code with it

### PR DESCRIPTION
**Pull request by ZuluPro**

### CODE REVIEW

**Comment by felixxm** [comment]
As far as I'm concerned that's a bad idea. It can cause settings conflict with other reusable apps. @kylef what do you think about it?

**Comment by ZuluPro** [comment]
@felixxm, How could it make conflicts ?

Variables are stored in ``request.settings`` and values are taken from ``django.conf.settings`` which contains ``REQUEST_``.

**Comment by felixxm** [comment]
You're right. I didn't look carefully enough at the `request.settings` changes.

**Comment by ZuluPro** [comment]
@felixxm @kylef Any news ?

**Comment by ZuluPro** [comment]
@felixxm @kylef Any news ?

**Comment by kylef** [comment]
I don't have a strong opinion either way. So I'm happy with these changes unless @felixxm has any objections.

**Comment by felixxm** [comment]
@ZuluPro Can you rebase from master?

**Comment by ZuluPro** [comment]
@felixxm Done !

**Comment by kylef** [comment]
Thanks @ZuluPro

**Pull request merged**
