### PR TITLE
Fixed #235 -- Added migration to change help_text of Request.is_ajax.

### LINKED ISSUE #235: Migration missing from released package
Latest release at the time (`django-request==1.6.0`) is missing a migration:

```
$ ./manage.py makemigrations --dry-run
Migrations for 'request':
  /Users/vmax/.virtualenvs/xxx/lib/python3.8/site-packages/request/migrations/0007_alter_request_is_ajax.py
    - Alter field is_ajax on request
```

This is probably caused by https://github.com/django-request/django-request/commit/372d9941a6a69c875d391c60ecde6be9e24f806d; altering `help_text` on the field triggers Django migration mechanism to see a change in the model.

### PR DESCRIPTION
**Pull request by vmax**
Fixes #235

### CODE REVIEW

**Comment by felixxm** [comment]
@vmax Thanks :+1:

**Comment by felixxm** [comment]
Welcome aboard :boat:

**Comment by felixxm** [comment]
Merged in d139ad739097c7ff60a0ef0d7faa12902f291af9.

**Comment by vmax** [comment]
@felixxm thank you! any ETA on when this can be released to PyPI?

**Comment by felixxm** [comment]
> @felixxm thank you! any ETA on when this can be released to PyPI?

I'm not sure, hopefully soon. There is one more issue that I'd like to fix before 1.6.1, see https://github.com/django-request/django-request/pull/234#issuecomment-998263414.

**Comment by felixxm** [comment]
@vmax django-request 1.6.1 is out :confetti_ball:

**Comment by vmax** [comment]
@felixxm thank you 🙂

**Pull request closed without merging**
